name: Sync from Hugging Face & Build Docker

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨 1 点运行（UTC 时间）
  workflow_dispatch:  # 手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Pull Hugging Face Space code
        run: |
          rm -rf hf_space
          git clone https://huggingface.co/spaces/skylerhe/qinglong hf_space

      - name: Copy Space files into workspace
        run: |
          cp -r hf_space/* ./
          rm -rf hf_space

      - name: Generate version tag
        id: tagger
        run: echo "TAG=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image with date tag and latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            skylerhe/qinglong:latest
            skylerhe/qinglong:${{ env.TAG }}
