name: Sync HF Space & Push Docker If Changed

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨 1 点
  workflow_dispatch:

jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq moreutils

      - name: Pull Hugging Face Space
        run: |
          rm -rf hf_space
          git clone https://huggingface.co/spaces/skylerhe/qinglong hf_space

      - name: Compute hash of pulled content
        run: |
          find hf_space -type f -exec sha256sum {} \; | sort -k 2 | sha256sum | cut -d ' ' -f1 > hf_hash.txt

      - name: Check if content has changed
        id: compare
        run: |
          if [ -f .last_hf_hash ]; then
            diff=$(diff hf_hash.txt .last_hf_hash || true)
            if [ -z "$diff" ]; then
              echo "no_change=true" >> $GITHUB_OUTPUT
            else
              echo "no_change=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "First run or no cache. Will proceed."
            echo "no_change=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit early if no changes
        if: steps.compare.outputs.no_change == 'true'
        run: echo "No changes in Hugging Face Space, skipping build."

      - name: Copy files from HF space
        if: steps.compare.outputs.no_change != 'true'
        run: |
          cp -r hf_space/* ./
          rm -rf hf_space

      - name: Save new hash
        if: steps.compare.outputs.no_change != 'true'
        run: cp hf_hash.txt .last_hf_hash

      - name: Generate version tag
        if: steps.compare.outputs.no_change != 'true'
        run: echo "TAG=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: steps.compare.outputs.no_change != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.compare.outputs.no_change != 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: steps.compare.outputs.no_change != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            skylerhe/qinglong:latest
            skylerhe/qinglong:${{ env.TAG }}

      - name: Commit updated hash
        if: steps.compare.outputs.no_change != 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .last_hf_hash
          git commit -m "update: sync HF Space hash on ${{ env.TAG }}" || echo "No changes to commit"
          git push || echo "No changes to push"
